import { Injectable } from '@nestjs/common';
import {
  SelectorOptions,
  GeneratedSelector,
} from './strategies/selector-strategy.interface';
import { isTestableElement } from './selector-utils';
import { TestAttributeStrategy } from './strategies/test-attribute.strategy';
import { PlaywrightStrategy } from './strategies/playwright.strategy';
import { SemanticStrategy } from './strategies/semantic.strategy';
import { RelationalStrategy } from './strategies/relational.strategy';
import { LayoutStrategy } from './strategies/layout.strategy';
import { CombinedStrategy } from './strategies/combined.strategy';
import { XPathStrategy } from './strategies/xpath.strategy';

@Injectable()
export class AdvancedSelectorGeneratorService {

  private readonly testAttributeStrategy = new TestAttributeStrategy();
  private readonly playwrightStrategy = new PlaywrightStrategy();
  private readonly semanticStrategy = new SemanticStrategy();
  private readonly relationalStrategy = new RelationalStrategy();
  private readonly layoutStrategy = new LayoutStrategy();
  private readonly combinedStrategy = new CombinedStrategy();
  private readonly xpathStrategy = new XPathStrategy();

  /**
   * Generate advanced CSS selectors based on W3Schools specification + Playwright optimizations
   * Long selectors are acceptable if they ensure uniqueness
   */
  generateSelectors(options: SelectorOptions): GeneratedSelector[] {
    const { element, document, prioritizeUniqueness, includePlaywrightSpecific, testableElementsOnly } = options;
    const selectors: GeneratedSelector[] = [];

    // Skip non-testable elements if requested
    if (testableElementsOnly && !isTestableElement(element)) {
      return [];
    }

    // 1. HIGHEST PRIORITY: Test-specific attributes (Playwright optimized)
    this.testAttributeStrategy.addTestSpecificSelectors(element, selectors, document);

    // 2. HIGH PRIORITY: Unique IDs (W3Schools compliant)
    this.testAttributeStrategy.addIdSelectors(element, selectors, document);

    // 3. PLAYWRIGHT SPECIFIC: Text and role selectors
    if (includePlaywrightSpecific) {
      this.playwrightStrategy.addPlaywrightSelectors(element, selectors, document);
    }

    // 3b. REMOVED: Native locators (getByRole, getByText, etc.) are Playwright API method
    // signatures, not CSS selectors. They should NOT be stored as selectors since they
    // require special resolveLocator() parsing. CSS equivalents like [role="button"]:has-text("Submit")
    // and [aria-label="..."] are already generated by the pipeline above.

    // 4. ADVANCED CSS: Semantic selectors (ARIA, etc.)
    this.semanticStrategy.addSemanticSelectors(element, selectors, document);

    // 5. STABLE ATTRIBUTE SELECTORS: Only stable, meaningful attributes
    this.semanticStrategy.addStableAttributeSelectors(element, selectors, document);

    // 6. COMPLEX CSS: Stable parent-child relationships
    this.relationalStrategy.addStableRelationalSelectors(element, selectors, document);

    // 7. PLAYWRIGHT CSS EXTENSIONS: Visibility, state, and text matching
    this.layoutStrategy.addVisibilitySelectors(element, selectors, document);
    this.layoutStrategy.addStateAttributeSelectors(element, selectors, document);
    this.combinedStrategy.addEnhancedTextSelectors(element, selectors, document);
    this.combinedStrategy.addDeepCombinatorSelectors(element, selectors, document);

    // 7b. C1.2: SIBLING-BASED SELECTORS: Form labels, button context, table cells
    this.relationalStrategy.addSiblingBasedSelectors(element, selectors, document);

    // 8. COMPREHENSIVE COMBINED SELECTORS: Multiple attributes for maximum uniqueness
    this.combinedStrategy.addComprehensiveCombinedSelectors(element, selectors, document);

    // 9. ULTIMATE FALLBACK: XPath for complex cases (only if needed)
    if (selectors.length < 3) {
      this.xpathStrategy.addXPathSelectors(element, selectors, document);
    }

    // REMOVED FRAGILE SELECTORS:
    // - Structural selectors (nth-child, nth-of-type) - break when DOM structure changes
    // - Class selectors - CSS classes change with styling frameworks and updates
    // - Layout-based selectors - deprecated by Playwright, viewport-dependent
    // - Functional pseudo-classes (:has, :not, :is) - low confidence, non-standard support

    // Sort by confidence and uniqueness, filter for high-confidence only
    return selectors
      .filter(s => s.confidence >= 0.75) // STRICT: Only robust selectors (user requirement)
      .sort((a, b) => {
        if (prioritizeUniqueness) {
          if (a.isUnique !== b.isUnique) return a.isUnique ? -1 : 1;
        }
        return b.confidence - a.confidence;
      })
      .slice(0, 10); // Return top 10 robust selectors
  }
}
